import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

// Dispute message interface
export interface DisputeMessage {
  _id: Types.ObjectId;
  content: string;
  sender: Types.ObjectId;
  senderType: 'buyer' | 'seller' | 'admin';
  senderEmail?: string;
  createdAt: Date;
  isInternal?: boolean; // Admin-only notes, not visible to users
}

// Dispute priority type
export type DisputePriority = 'low' | 'medium' | 'high' | 'urgent';

// Dispute status type
export type DisputeStatus = 'open' | 'under_review' | 'resolved' | 'closed';

// Dispute reason categories
export type DisputeReason =
  | 'payment_issue'
  | 'quality_issue'
  | 'delivery_delay'
  | 'documentation_problem'
  | 'communication_issue'
  | 'pricing_dispute'
  | 'contract_breach'
  | 'other';

@Schema({ timestamps: true })
export class TradeDispute extends Document {
  @Prop({ type: Types.ObjectId, ref: 'Trade', required: true, index: true })
  trade: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  raisedBy: Types.ObjectId;

  @Prop({ required: true, enum: ['buyer', 'seller'] })
  raisedByRole: 'buyer' | 'seller';

  @Prop({ required: true })
  raisedByEmail: string;

  @Prop({
    required: true,
    enum: [
      'payment_issue',
      'quality_issue',
      'delivery_delay',
      'documentation_problem',
      'communication_issue',
      'pricing_dispute',
      'contract_breach',
      'other',
    ],
  })
  reason: DisputeReason;

  @Prop({ required: true })
  description: string;

  @Prop({
    default: 'medium',
    enum: ['low', 'medium', 'high', 'urgent'],
    index: true,
  })
  priority: DisputePriority;

  @Prop({
    default: 'open',
    enum: ['open', 'under_review', 'resolved', 'closed'],
    index: true,
  })
  status: DisputeStatus;

  @Prop({ type: Types.ObjectId, ref: 'AdminUser' })
  assignedAdmin?: Types.ObjectId;

  @Prop()
  assignedAdminEmail?: string;

  @Prop()
  assignedAt?: Date;

  @Prop()
  resolutionNotes?: string;

  @Prop()
  resolvedAt?: Date;

  @Prop({ type: Types.ObjectId, ref: 'AdminUser' })
  resolvedBy?: Types.ObjectId;

  @Prop()
  resolvedByEmail?: string;

  @Prop()
  closedAt?: Date;

  @Prop({ type: Types.ObjectId, ref: 'AdminUser' })
  closedBy?: Types.ObjectId;

  @Prop({ type: [Object], default: [] })
  messages: DisputeMessage[];

  // Timestamps (auto-generated by Mongoose)
  createdAt: Date;
  updatedAt: Date;
}

export const TradeDisputeSchema = SchemaFactory.createForClass(TradeDispute);

// Add indexes for common queries
TradeDisputeSchema.index({ status: 1, priority: -1, createdAt: -1 });
TradeDisputeSchema.index({ assignedAdmin: 1, status: 1 });
TradeDisputeSchema.index({ trade: 1 });
